# Generated by Django 3.0.8 on 2020-07-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200705_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_path',
            field=models.CharField(default='Three Minute Meal.mp4', max_length=200),
            preserve_default=False,
        ),
    ]
