# Generated by Django 3.0.8 on 2020-07-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_video_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, unique=True)),
                ('answer', models.CharField(max_length=400, unique=True)),
            ],
        ),
    ]
