# Generated by Django 3.0.8 on 2020-07-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200707_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_on',
        ),
    ]
