# Generated by Django 3.0.8 on 2020-08-01 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficultyLeft',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='post',
            name='trailer1',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='trailer2',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='trailer3',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
