# Generated by Django 3.0.8 on 2020-08-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200801_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
